### ISSUE TITLE
Problem with Notes

### ISSUE THREAD

**Issue by aduh95** [jaime-olivares/yuml-diagram#1]
With the last update, an old issue has come back: https://github.com/jaime-olivares/vscode-yuml/issues/23

```yuml
// {type:class}
// {direction:topDown}
[note: You can stick notes on diagrams too!{bg:cornsilk}]
[Customer]<>1-orders 0..*>[Order]
[Order]-[note:asdf]
```

This fails with "Error composing the diagram".

I have a fix for it: https://github.com/aduh95/yuml2svg/commit/9f8acd4a40559c51b244e4c4769bdf2065a9ecd0 and https://github.com/aduh95/yuml2svg/commit/0b9f53df208b0998eac7d342ec29e91e7ef35d94.

Do you want me to open a PR?

**Comment by jaime-olivares** [comment]
Sure, please only the minimum required changes, for better understanding.

**Comment by jaime-olivares** [comment]
Tested and published. Thanks.
