### ISSUE TITLE
Make it run in the browser

### ISSUE THREAD

**Issue by mojo2012** [jaime-olivares/yuml-diagram#11]
It would be awesome to make it work in a browser environment. I‘d love to write a docsify plugin.
I tried browserify but the resulting 8.5MB file is hardly usable.
Cheers, matti

**Comment by aduh95** [comment]
I have made [a fork](https://github.com/aduh95/yuml2svg/blob/master/README.md) that works on the browser: https://aduh95.github.io/yuml2svg-playground/

It uses Viz.js v2 which is significantly smaller than using v1.

**Comment by mojo2012** [comment]
Thanks! It would be awesome if the npm package would contain an already bundled version, that just needs to be included in the HTML (like **dist/yuml2svg.min.js**).
I played around with browserify but can't seem to make it work. Btw, I don't want to include any kind of build step!
Thanks for your help.

**Comment by jaime-olivares** [comment]
@mojo2012 
I have tried with the following from the project's root:
- `browserify index.js -o yuml-diagram.js` (7Mb+)
- `browserify index.js -g uglifyify -o yuml-diagram.min.js` (5Mb+)

You will need to install `browserify` and `uglifyify` npm packages.

Let me know if that works for you and how did you used it.

**Comment by jaime-olivares** [comment]
Wait! now I have <1.8 Mb, after removing the dependency on JSDom.
Try with version 1.1.0

**Comment by jaime-olivares** [comment]
This workitem is done. Have a look at:
https://github.com/jaime-olivares/yuml-diagram#browserified-distribution
