### ISSUE TITLE
Background-Color for Class with Attributes

### ISSUE THREAD

**Issue by chezwicker** [jaime-olivares/yuml-diagram#14]
In a class diagram, the following does not render the background color:
`[Class|Attribute{bg:green}]`
This does:
`[Class{bg:green}]`
It does work on yuml.me ([example](https://yuml.me/edit/f2e377f0)), so I expect the syntax is right.

Also, white text on green background is hard to read, are there cases where black on green doesn't work?

**Comment by erikrenaud** [comment]
Have the same problem - not sure if it is a regression.

Also in this case, the COLOR and ATTRIBUTES don't show up...
[Class|Attribute{bg:green}]

**Comment by yutao-huang** [comment]
@jaime-olivares: Can you publish a NPM package with this fix? Thanks!
