### ISSUE TITLE
Not support handwrite style

### ISSUE THREAD

**Issue by linkjam** [jaime-olivares/yuml-diagram#17]
it seems that there is no way to set the appearnce style of the UML,such as the handwriting style called "scruffy"

**Comment by jaime-olivares** [comment]
No, that feature is not in the roadmap.

**Comment by mvsouza** [comment]
I was looking for this too, that king of style usually give a cense of sketch, and my intent on of showing uml arch. is give a feel of WIP, never a final solution.

Not having it is a buzz kill, but I've seen the backlog, definitely thats not a priority. 

Would you consider labeling it as for later?
 I would  be glad to do it.
