### ISSUE TITLE
How to use angle bracket "<" in a class?

### ISSUE THREAD

**Issue by SXongin** [jaime-olivares/yuml-diagram#18]
It seems that the angle bracket have strange behavior, may the image says my mind.
![image](https://user-images.githubusercontent.com/22723121/55316640-728fb800-54a1-11e9-9bf4-c490090368b7.png)
![image](https://user-images.githubusercontent.com/22723121/55316776-b4206300-54a1-11e9-9335-270f01558cd3.png)

**Comment by jaime-olivares** [comment]
Published in https://www.npmjs.com/package/yuml-diagram/v/1.0.10
