### ISSUE TITLE
Update wiki: add examples

### ISSUE THREAD

**Issue by rkristelijn** [jaime-olivares/yuml-diagram#19]
Hi Jaime, I've tried to update your wiki page, however the process seems different than from code. Anyways; here's my proposal attached.
[Archive.zip](https://github.com/jaime-olivares/yuml-diagram/files/3227436/Archive.zip)

**Comment by jaime-olivares** [comment]
Hi @rkristelijn 
Thanks for your contribution. I have updated the wiki.
