### ISSUE TITLE
Improve extensibility & change `processYumlDocument`

### ISSUE THREAD

**Issue by GerkinDev** [jaime-olivares/yuml-diagram#22]
Hi,

Your lib seems very interesting. But I can't find a way to choose where to save files (on node), or where it is added in the page. It would be convinient if there were an API method that returns the SVG generated, without doing anything more (which is more application-dependant).

Switch between documents types is hardcoded. It would be great if it were extensible so that anyone can register processing functions simply.

A proper API documentation, informing about methods signatures would be great too.

So what do you plan to do with the lib ?

**Comment by jaime-olivares** [comment]
This was already possible, as in the example:
````
var yuml  = new yuml_diagram();
var svg = yuml.processYumlDocument(yumlText, false);
````
