### ISSUE TITLE
Are the block rows supported?

### ISSUE THREAD

**Issue by iegik** [jaime-olivares/yuml-diagram#23]
version: ^1.1.0

As mentioned in #4 and [README.md](../blob/master/README.md), rows should be supported.

```
// {type:class}

[Foo|Bar]
```

- shows block with text "A0"

<img width="70" alt="Screenshot 2019-09-18 at 11 24 45" src="https://user-images.githubusercontent.com/175293/65130876-f9f8c580-da06-11e9-9629-c27dd0e4aac3.png">

And rendered code from example:

[![Edit yuml-diagram](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-dew-gqohh?fontsize=14&view=preview)

**Comment by jaime-olivares** [comment]
Solved with version 1.2
