### ISSUE TITLE
Wrong Path to data/rgb.txt in loadColors function (file src/utils/yuml2dot-utils.js)

### ISSUE THREAD

**Issue by kanian** [jaime-olivares/yuml-diagram#26]
Hi all, 
when debugging yuml-diagram in vscode, I run into a 'file not found error":
 
![Screenshot from 2019-11-28 13-59-19](https://user-images.githubusercontent.com/626923/69812294-baf5a600-11e7-11ea-8300-74b740d4af9a.png)

The call stack leading to the error is the following:

![Screenshot from 2019-11-28 13-57-14](https://user-images.githubusercontent.com/626923/69812353-e7112700-11e7-11ea-9588-83d58c111017.png)

yumlExample.js has the following content: 
![Screenshot from 2019-11-28 14-07-16](https://user-images.githubusercontent.com/626923/69812668-87674b80-11e8-11ea-9ef3-9cffe71823ec.png)

To fix that, in the `loadColors` function, rather than having:
```
var rgb = fs.readFileSync(__dirname + "/../data/rgb.txt", {encoding:"utf8", flag:"r"}).split('\n');
```
We should have:
```
var rgb = fs.readFileSync(__dirname + "/../../data/rgb.txt", {encoding:"utf8", flag:"r"}).split('\n');
```
I will make a pull request for this.

Regards,

**Comment by jaime-olivares** [comment]
I will attend this soon

**Comment by jaime-olivares** [comment]
This is fixed. Thanks for providing the PR.

**Comment by kanian** [comment]
Nice.
