### ISSUE TITLE
NPM module not finding rgb.txt file!

### ISSUE THREAD

**Issue by chaeron** [jaime-olivares/yuml-diagram#28]
Found an issue using the npm module where it won't parse {bg:colour} directives, since it can't find the rgb.txt file.  This causes an exception to be thrown, but it's caught and all you see is an "Error parsing the yUML file" error as output in the svg.

In src/util/yuml2dot-utils, the following line 

`var rgb = fs.readFileSync(__dirname + "/../data/rgb.txt", {encoding:"utf8", flag:"r"}).split('\n');`

should read:

`var rgb = fs.readFileSync(__dirname + "/../../data/rgb.txt", {encoding:"utf8", flag:"r"}).split('\n');`

since the data directory is two levels up from where yuml2dot-utils is located.

**Comment by jaime-olivares** [comment]
Duplicated in #26 Will fix with #27
