### ISSUE TITLE
Class diagram, fields not rendering....

### ISSUE THREAD

**Issue by chaeron** [jaime-olivares/yuml-diagram#29]
If I code something like this:

`[Node|+fld1: string;+fld2:string;-fld3: number]`

I don't get the fields rendered into the svg as part of the class.  

yuml.me renders this style of yuml just fine, as does the VS Code plugin.  Though the VS Code plugin doesn't seem to set the text colour right when you do this and it breaks the middle fld2 line across two lines.

**Comment by jaime-olivares** [comment]
Solved in version 1.2
