### ISSUE TITLE
Class diagram entity's methods causing entity's class not to render

### ISSUE THREAD

**Issue by nerdfiles** [jaime-olivares/yuml-diagram#35]
I'm attempting to process the class diagram provided in the wiki's examples that has the following line:

```
[Order]*-*>[Product|EAN_Code|promo_price()]
```

What's happening is the Product class is rendered as "A5," which seems to be caused by the presence of a method inside the class:

<img width="405" alt="Screen Shot 2021-03-31 at 10 39 16 AM" src="https://user-images.githubusercontent.com/102306/113171718-60ba8a00-920d-11eb-86a8-bfd1acc7e3e2.png">

I'm not sure if it is due to the version of node I'm running. Thoughts?

**Comment by jaime-olivares** [comment]
Solved in version 1.2
