### ISSUE TITLE
Readme shows black on black img for sequence diag in dark mode

### ISSUE THREAD

**Issue by Morriz** [jaime-olivares/yuml-diagram#36]
FYI:
![605F1F29-D3F3-4794-AC39-7C4C2FC00A3E](https://user-images.githubusercontent.com/941865/167271859-4973d7d7-c6f3-45eb-839d-18e773a214da.png)

But tnx for your plugin!

**Comment by jaime-olivares** [comment]
Got it, will fix soon

**Comment by jaime-olivares** [comment]
done
