### ISSUE TITLE
semicolons -> \n in class diagrams

### ISSUE THREAD

**Issue by greg-murray-volusion** [jaime-olivares/yuml-diagram#4]
It's not putting in the correct line breaks in the svg.

    // {type:class}
    // {direction:leftToRight}
    // {generate:true}

    [Customer|Forename;Surname;Email|Save()]

![image](https://user-images.githubusercontent.com/22917554/41045814-c84d695a-696e-11e8-9774-09de544adc7c.png)

**Comment by jaime-olivares** [comment]
Hi, thanks for reporting, I will look at it

**Comment by greg-murray-volusion** [comment]
Cool, thanks for the quick response!
