### ISSUE TITLE
Brackets in class diagrams preview

### ISSUE THREAD

**Issue by jaime-olivares** [jaime-olivares/yuml-diagram#6]
As reported in https://github.com/jaime-olivares/vscode-yuml/issues/43

There seems to be a problem with in class diagrams preview, the class name was displayed enclosed by braces.
When the class was defined including attributes the braces open before the class name and close after last attribute.

I can see it happens with topDown but not with leftToRight

![image](https://user-images.githubusercontent.com/6194083/41102576-e149d8b2-6a2c-11e8-9b5d-7cb3a57c3130.png)

**Comment by aduh95** [comment]
I think this is related to these lines:

https://github.com/jaime-olivares/yuml-diagram/blob/2df5102f170f221be60b0986c62a953a5f44723f/src/class-diagram.js#L139-L143

Related to this, in the state diagram rendering module:

https://github.com/jaime-olivares/yuml-diagram/blob/2df5102f170f221be60b0986c62a953a5f44723f/src/state-diagram.js#L87-L88

**Comment by garkin** [comment]
Same issues with state diagrams, `yUML 3.1.2`

```yuml
// {type: state}
(Empty)EnterCave->(Cave|RoomChoice)
(Cave)Won->(Empty)
(Cave)Lost->(Empty)
```

![image](https://user-images.githubusercontent.com/422774/46582839-8f5dac80-ca77-11e8-92cd-d3ea6f147c7e.png)
