### ISSUE TITLE
Note not showing in the Sequence diagram

### ISSUE THREAD

**Issue by benjamin-thomas** [jaime-olivares/yuml-diagram#9]
Hi, I'm evaluating your vscode extension: looks brilliant so far.

I think there is a typo here though:

![image](https://user-images.githubusercontent.com/1557738/42923415-a55d85e6-8b25-11e8-83bd-c7d3dc198f33.png)

It seems the syntax should be:

    Note         [Actor]->[note: a note message]

Not:

    Note         [Actor]-[note: a note message]

---

Source: https://github.com/jaime-olivares/yuml-diagram/wiki

**Comment by benjamin-thomas** [comment]
Ok I see that the same syntax is documented for other diagram types, and seems to work elsewhere.

So it must be a parser here.

Just to be clear, here are 2 screenshots:

![image](https://user-images.githubusercontent.com/1557738/42923929-3bc19fd4-8b28-11e8-98b5-410c472c6613.png)

![image](https://user-images.githubusercontent.com/1557738/42923834-dbf1f4aa-8b27-11e8-8766-514abd7e7604.png)

**Comment by jaime-olivares** [comment]
Thanks, I will review soon.

**Comment by jaime-olivares** [comment]
Now it shall be working as expected (use a single dash)
